### ISSUE TITLE
build error

### ISSUE THREAD

**Issue by dingweihua** [kaiyuan10nian/kaiyuan10nian#1]
➜  kaiyuan10nian git:(master) ✗ go build -o . main.go 
./main.go:20:6: undefined: CollectRoute

同时，CollectRoute直接放到main下是否合适？是不是最好有一个专门的routes package？

**Comment by kaiyuan10nian** [comment]
我已收到你发的信息
回头答复你·······

**Comment by kaiyuan10nian** [comment]
嗯嗯 非常棒，完全可以的，我只是想后面去区分逻辑层、应用层、数据层留的小尾巴，下次更新的时候我改过去吧
