### ISSUE TITLE
"gorm.io/gorm"和"github.com/jinzhu/gorm"版本不一样

### ISSUE THREAD

**Issue by 18208202069** [kaiyuan10nian/kaiyuan10nian#2]
`// db, err := gorm.Open(driverName, args)`
 `db, err := gorm.Open(mysql.Open(dsn), &gorm.Config{})`
方法不太一样，而且github更新很快
![image](https://user-images.githubusercontent.com/56058515/161562260-0a7cdec4-a1c8-4875-9591-2a439f1d6ca6.png)
![image](https://user-images.githubusercontent.com/56058515/161562800-d11bc43b-d8a0-4d8e-8a04-69f5d396b111.png)
项目迁移到这里了https://github.com/go-gorm/gorm
来早了，坐等更新，加油，这次别鸽

**Comment by kaiyuan10nian** [comment]
[good]确实是哦，我当时还真没有去比较过这两个，涨知识了 多谢

**Comment by kaiyuan10nian** [comment]
已修复
