### ISSUE TITLE
关于文章：[Blog项目骨架搭建---Go语言（第一阶段）的两点建议

### ISSUE THREAD

**Issue by changpingdengdeng** [kaiyuan10nian/kaiyuan10nian#3]
1. gin安装：go get -u [http://github.com/gin-gonic/gin](https://link.zhihu.com/?target=http%3A//github.com/gin-gonic/gin) 应为 go get -u [github.com/gin-gonic/gin](https://github.com/gin-gonic/gin)。
2. 在数据结构设计中，grom的数据结构应当为嵌入而非继承 ，在go中不存在继承这个概念。
> gorm.Model这个标记一个结构中有一个结构中没有，那他是用来干什么的呢？其实这就相当于是继承，加上这个后就相当于继承了Model，不加这个代表不继承Model。

**Comment by kaiyuan10nian** [comment]
嗯嗯 多谢多谢，确实是这样的

**Comment by kaiyuan10nian** [comment]
嗯嗯 多谢指点，针对第一个问题 我已经修复，原因是当时复制链接的时候自动给我转成了http，我也没有注意。惭愧
第二个是我表述不对，多谢指正
