### ISSUE TITLE
logger封装成单独的pkg是不是更好？

### ISSUE THREAD

**Issue by dingweihua** [kaiyuan10nian/kaiyuan10nian#5]
当前的logger是放在config pkg下的，封装成单独的pkg是不是更好一些？这样也可以方便写unittest。

列出几个参考例子：
https://github.com/xinliangnote/go-gin-api/tree/master/pkg/logger
https://github.com/kott/go-service-example/tree/main/pkg/utils/log

**Comment by kaiyuan10nian** [comment]
嗯 我去学习一下
