### ISSUE TITLE
InitConfig和initLogger建议改成init函数单独一个文件处理

### ISSUE THREAD

**Issue by McDonald755** [kaiyuan10nian/kaiyuan10nian#7]
如果读取配置用的是viper的包还可以加上热更新配置
appViper := viper.New()
appViper.WatchConfig()
	appViper.OnConfigChange(func(in fsnotify.Event) {
		//这里重新初始化链接
		initDB(appViper)
                 initRedis(appViper)
		xxxxx
	})

**Comment by kaiyuan10nian** [comment]
嗯嗯 这里懒省劲了
