### ISSUE TITLE
代码 clone 报错

### ISSUE THREAD

**Issue by kcxg** [kaiyuan10nian/kaiyuan10nian#8]
代码clone 报错

error: invalid path 'doc/Go项目实战断更2月后的"诈尸".md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by kaiyuan10nian** [comment]
我已收到你发的信息
回头答复你·······

**Comment by kcxg** [comment]
等待中。。。。

**Comment by kcxg** [comment]
$ git clone https://github.com/kaiyuan10nian/kaiyuan10nian.git
Cloning into 'kaiyuan10nian'...
remote: Enumerating objects: 287, done.
remote: Counting objects: 100% (113/113), done.
remote: Compressing objects: 100% (67/67), done.
remote: Total 287 (delta 64), reused 81 (delta 41), pack-reused 174
Receiving objects: 100% (287/287), 29.19 MiB | 2.22 MiB/s, done.
Resolving deltas: 100% (128/128), done.
error: invalid path 'doc/Go项目实战断更2月后的"诈尸".md'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by kcxg** [comment]
@kaiyuan10nian

**Comment by kaiyuan10nian** [comment]
我已收到你发的信息
回头答复你·······

**Comment by kaiyuan10nian** [comment]
原因：'doc/Go项目实战断更2月后的"诈尸".md'这个文件中包含了特殊字符，在mac中是默认可以的，在Windows中不行
修复方案：我已经把路径中的特殊字符去掉了，你再试一下
